### ISSUE TITLE
错误依旧存在

### ISSUE THREAD

**Issue by luoxianwu** [hexiangdong2020/zephyr_esp32_blinky#1]
我按照以下链接中的指南安装了 Zephyr 开发环境（我注意到你的版本是 3.3.0，最新版本是 3.7.99，我使用的是最新版本）： https://docs.zephyrproject.org/latest/develop/getting_started/index.html

在执行以下步骤时遇到了相同的错误： west build -p always -b esp32_devkitc_wroom samples/basic/blinky （注意，我将板卡名称更改为 esp32_devkitc_wroom）

我按照你的建议添加了 samples/basic/blinky/boards/esp32_devkitc_wroom.overlay 文件，再次进行构建，但错误依旧存在。

我是否遗漏了什么？ 谢谢！ Xian

![image](https://github.com/user-attachments/assets/a865047a-eda2-4d0c-ba3e-5ee3f8fbc98c)

**Comment by luoxianwu** [comment]
我还尝试将您的代码克隆到 ~/zephyrproject/zephyr
west build -p always -b esp32 zephyr_esp32_blinky
但得到同样的错误。

**Comment by hexiangdong2020** [comment]
不同版本的Zephyr的配置可能有差异，你是否尝试过在旧版本上进行编译呢？

**Comment by hexiangdong2020** [comment]
我已经合并了你提交的文件
